# Generated by Django 4.2.16 on 2024-09-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_cctv_rtsp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracker_id", models.IntegerField()),
                ("status", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="detections/"),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.cctv"
                    ),
                ),
            ],
        ),
    ]
