# Generated by Django 4.2.16 on 2024-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_detection"),
    ]

    operations = [
        migrations.AddField(
            model_name="cctv",
            name="running_status",
            field=models.BooleanField(default=False),
        ),
    ]
