# Generated by Django 4.2.16 on 2024-09-25 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_cctv_start_detection"),
    ]

    operations = [
        migrations.CreateModel(
            name="tracker_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracker_id", models.IntegerField()),
                ("status", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="detection",
            name="status",
        ),
        migrations.AlterField(
            model_name="detection",
            name="tracker_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.tracker_status",
            ),
        ),
    ]
