# Generated by Django 4.2.16 on 2024-09-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_tracker_status_remove_detection_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="status",
            field=models.CharField(default="UNKNOWN", max_length=10),
        ),
        migrations.AlterField(
            model_name="detection",
            name="tracker_id",
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name="tracker_status",
        ),
    ]
