# Generated by Django 4.2.16 on 2024-09-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_detection_status_alter_detection_tracker_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="tracker_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracker_id", models.CharField(max_length=100)),
                ("status", models.CharField(default="Unknown", max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="detection",
            name="status",
        ),
        migrations.RemoveField(
            model_name="detection",
            name="tracker_id",
        ),
        migrations.AddField(
            model_name="detection",
            name="tracker",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.tracker_status",
            ),
        ),
    ]
