# Generated by Django 4.2.16 on 2024-09-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_tracker_status_remove_detection_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker_status",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="detection",
            name="camera",
            field=models.CharField(max_length=100),
        ),
    ]
