# Generated by Django 4.2.16 on 2024-09-26 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_tracker_status_completed_alter_detection_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker_status",
            name="last_detection_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
