# Generated by Django 4.2.16 on 2024-09-27 03:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_tracker_status_last_detection_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker_status",
            name="last_detection_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("camera", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                ("license_plate", models.CharField(max_length=100)),
                (
                    "license_plate_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="license_plates/"
                    ),
                ),
                (
                    "tracker",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tracker_status",
                    ),
                ),
            ],
        ),
    ]
