# Generated by Django 4.2.16 on 2024-09-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_tracker_status_last_detection_time_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker_status",
            name="camera",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.cctv",
            ),
        ),
    ]
