# Generated by Django 4.2.16 on 2024-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_tracker_status_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker_status",
            name="category",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="tracker_status",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
