# Generated by Django 4.2.16 on 2024-09-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_tracker_status_category_alter_tracker_status_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracker_status",
            name="category",
        ),
        migrations.AlterField(
            model_name="tracker_status",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
