# Generated by Django 4.2.16 on 2024-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_remove_detection_id_alter_detection_unique_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracker_status",
            name="camera",
        ),
        migrations.RemoveField(
            model_name="tracker_status",
            name="id",
        ),
        migrations.AddField(
            model_name="tracker_status",
            name="category",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="detection",
            name="camera",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="detection",
            name="tracker",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tracker_status",
            name="tracker_id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(default="UNREGISTERED", max_length=100),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="tracker",
            field=models.CharField(max_length=100),
        ),
    ]
