# Generated by Django 4.2.16 on 2024-09-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_tracker_status_camera_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detection",
            name="tracker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.tracker_status",
            ),
        ),
    ]
