# Generated by Django 4.2.16 on 2024-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_vehicle_tracker"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("script_name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
