# Generated by Django 4.2.16 on 2024-10-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_scriptstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scriptstatus",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
